aurora_data_api-0.4.0.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
aurora_data_api-0.4.0.dist-info/LICENSE,sha256=xx0jnfkXJvxRnG63LTGOxlggYnIysveWIZ6H3PNdCrQ,11357
aurora_data_api-0.4.0.dist-info/METADATA,sha256=yk52lFGYOANTOwVrxSKUUybiP4_wjPHHZcH9AZ9cpHg,6833
aurora_data_api-0.4.0.dist-info/RECORD,,
aurora_data_api-0.4.0.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
aurora_data_api-0.4.0.dist-info/WHEEL,sha256=G16H4A3IeoQmnOrYV4ueZGKSjhipXx8zc8nu9FGlvMA,92
aurora_data_api-0.4.0.dist-info/top_level.txt,sha256=Je34FkllNLpNVkxy87rGCKdwpn8Eu_XVsAaYDYmHp3E,16
aurora_data_api/__init__.py,sha256=r4n8vdrs_fPIeS7dNm0YMWq5CyAv9Dn-VWd1DuvOkRY,17943
aurora_data_api/__pycache__/__init__.cpython-310.pyc,,
aurora_data_api/__pycache__/exceptions.cpython-310.pyc,,
aurora_data_api/__pycache__/mysql_error_codes.cpython-310.pyc,,
aurora_data_api/__pycache__/postgresql_error_codes.cpython-310.pyc,,
aurora_data_api/exceptions.py,sha256=Ivnau-oZwVhREA0PznpQHcZL_kRWF9r2a-Z96jTE2ZA,1093
aurora_data_api/mysql_error_codes.py,sha256=pDgaKxOxZ0gwhwqUgSPSpTMZGQaHvx4KzBIl8Sd70qw,29340
aurora_data_api/postgresql_error_codes.py,sha256=xG7CI7GXFsFgDAbkPrQiYbYFhdzQs-UwiS_DvaXUNUw,9629
